-- GENERATED by scripts/generate_migrations.py from app/models. DO NOT EDIT BY HAND.

-- Tables, constraints, indexes and updated_at triggers.

-- organizations
CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  slug text NOT NULL,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  retention_days integer,
  CONSTRAINT organizations_slug_key UNIQUE (slug)
);
DROP TRIGGER IF EXISTS trg_organizations_updated_at ON public.organizations;
CREATE TRIGGER trg_organizations_updated_at BEFORE UPDATE ON public.organizations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  email text NOT NULL,
  full_name text,
  avatar_url text,
  default_org_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_profiles_default_org_id ON public.profiles (default_org_id);
DROP TRIGGER IF EXISTS trg_profiles_updated_at ON public.profiles;
CREATE TRIGGER trg_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- organization_members
CREATE TABLE IF NOT EXISTS public.organization_members (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'member',
  CONSTRAINT organization_members_role_check CHECK (role IN ('owner', 'admin', 'legal_reviewer', 'contract_manager', 'member', 'viewer')),
  CONSTRAINT organization_members_id_org_key UNIQUE (id, org_id),
  CONSTRAINT organization_members_org_id_user_id_key UNIQUE (org_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_organization_members_user_id ON public.organization_members (user_id);
DROP TRIGGER IF EXISTS trg_organization_members_updated_at ON public.organization_members;
CREATE TRIGGER trg_organization_members_updated_at BEFORE UPDATE ON public.organization_members FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- contracts
CREATE TABLE IF NOT EXISTS public.contracts (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  title text NOT NULL,
  contract_type text NOT NULL DEFAULT 'unknown',
  status text NOT NULL DEFAULT 'draft',
  effective_date date,
  expiration_date date,
  auto_renews boolean,
  renewal_notice_days integer,
  renewal_term_months integer,
  governing_law text,
  payment_terms text,
  currency text,
  total_value double precision,
  current_version_id uuid,
  owner_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  summary text,
  analysis_status text NOT NULL DEFAULT 'pending',
  review_status text NOT NULL DEFAULT 'unreviewed',
  business_risk_score double precision,
  extraction_uncertainty_score double precision,
  is_demo boolean NOT NULL DEFAULT false,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  deleted_at timestamptz,
  CONSTRAINT contracts_contract_type_check CHECK (contract_type IN ('msa', 'sow', 'saas_subscription', 'nda', 'employment', 'lease', 'license', 'purchase', 'services', 'amendment', 'other', 'unknown')),
  CONSTRAINT contracts_status_check CHECK (status IN ('draft', 'in_review', 'active', 'expiring', 'expired', 'terminated', 'archived')),
  CONSTRAINT contracts_analysis_status_check CHECK (analysis_status IN ('pending', 'running', 'completed', 'needs_review', 'failed')),
  CONSTRAINT contracts_review_status_check CHECK (review_status IN ('unreviewed', 'needs_review', 'approved', 'rejected', 'corrected')),
  CONSTRAINT contracts_id_org_key UNIQUE (id, org_id)
);
CREATE INDEX IF NOT EXISTS idx_contracts_org_id_status ON public.contracts (org_id, status);
CREATE INDEX IF NOT EXISTS idx_contracts_org_id_expiration_date ON public.contracts (org_id, expiration_date);
CREATE INDEX IF NOT EXISTS idx_contracts_org_id_deleted_at ON public.contracts (org_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_contracts_org_id ON public.contracts (org_id);
CREATE INDEX IF NOT EXISTS idx_contracts_current_version_id ON public.contracts (current_version_id);
CREATE INDEX IF NOT EXISTS idx_contracts_owner_id ON public.contracts (owner_id);
CREATE INDEX IF NOT EXISTS idx_contracts_created_by ON public.contracts (created_by);
DROP TRIGGER IF EXISTS trg_contracts_updated_at ON public.contracts;
CREATE TRIGGER trg_contracts_updated_at BEFORE UPDATE ON public.contracts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- contract_versions
CREATE TABLE IF NOT EXISTS public.contract_versions (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL,
  version_number integer NOT NULL DEFAULT 1,
  label text NOT NULL DEFAULT 'Original',
  document_role text NOT NULL DEFAULT 'original',
  supersedes_version_id uuid,
  effective_date date,
  is_current boolean NOT NULL DEFAULT true,
  extraction jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  CONSTRAINT contract_versions_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT contract_versions_document_role_check CHECK (document_role IN ('original', 'amendment', 'addendum', 'schedule', 'revised')),
  CONSTRAINT contract_versions_supersedes_version_id_fkey FOREIGN KEY (supersedes_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE SET NULL (supersedes_version_id),
  CONSTRAINT contract_versions_id_org_key UNIQUE (id, org_id),
  CONSTRAINT contract_versions_contract_id_version_number_key UNIQUE (contract_id, version_number)
);
CREATE INDEX IF NOT EXISTS idx_contract_versions_org_id ON public.contract_versions (org_id);
CREATE INDEX IF NOT EXISTS idx_contract_versions_supersedes_version_id ON public.contract_versions (supersedes_version_id);
CREATE INDEX IF NOT EXISTS idx_contract_versions_created_by ON public.contract_versions (created_by);
DROP TRIGGER IF EXISTS trg_contract_versions_updated_at ON public.contract_versions;
CREATE TRIGGER trg_contract_versions_updated_at BEFORE UPDATE ON public.contract_versions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- documents
CREATE TABLE IF NOT EXISTS public.documents (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL,
  contract_version_id uuid NOT NULL,
  filename text NOT NULL,
  mime_type text NOT NULL,
  size_bytes integer NOT NULL,
  file_hash text NOT NULL,
  storage_path text NOT NULL,
  page_count integer NOT NULL DEFAULT 0,
  page_basis text NOT NULL DEFAULT 'physical',
  is_scanned boolean NOT NULL DEFAULT false,
  ocr_used boolean NOT NULL DEFAULT false,
  ocr_confidence double precision,
  indexing_status text NOT NULL DEFAULT 'pending',
  indexing_progress double precision NOT NULL DEFAULT 0.0,
  indexing_error text,
  index_attempts integer NOT NULL DEFAULT 0,
  heartbeat_at timestamptz,
  embedding_model text,
  embedding_dim integer,
  chunk_count integer NOT NULL DEFAULT 0,
  indexed_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  uploaded_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  CONSTRAINT documents_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT documents_contract_version_id_fkey FOREIGN KEY (contract_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE CASCADE,
  CONSTRAINT documents_indexing_status_check CHECK (indexing_status IN ('pending', 'extracting', 'ocr', 'chunking', 'embedding', 'indexed', 'failed')),
  CONSTRAINT documents_id_org_key UNIQUE (id, org_id),
  CONSTRAINT documents_org_id_file_hash_key UNIQUE (org_id, file_hash)
);
CREATE INDEX IF NOT EXISTS idx_documents_contract_id ON public.documents (contract_id);
CREATE INDEX IF NOT EXISTS idx_documents_contract_version_id ON public.documents (contract_version_id);
CREATE INDEX IF NOT EXISTS idx_documents_indexing_status ON public.documents (indexing_status);
CREATE INDEX IF NOT EXISTS idx_documents_uploaded_by ON public.documents (uploaded_by);
DROP TRIGGER IF EXISTS trg_documents_updated_at ON public.documents;
CREATE TRIGGER trg_documents_updated_at BEFORE UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- document_chunks
CREATE TABLE IF NOT EXISTS public.document_chunks (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  document_id uuid NOT NULL,
  contract_id uuid NOT NULL,
  contract_version_id uuid NOT NULL,
  chunk_index integer NOT NULL,
  text text NOT NULL,
  page_number integer NOT NULL,
  page_end integer NOT NULL,
  section_reference text,
  section_title text,
  clause_type text NOT NULL DEFAULT 'other',
  char_start integer NOT NULL DEFAULT 0,
  char_end integer NOT NULL DEFAULT 0,
  token_estimate integer NOT NULL DEFAULT 0,
  text_hash text NOT NULL,
  embedded boolean NOT NULL DEFAULT false,
  CONSTRAINT document_chunks_document_id_fkey FOREIGN KEY (document_id, org_id) REFERENCES public.documents (id, org_id) ON DELETE CASCADE,
  CONSTRAINT document_chunks_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT document_chunks_contract_version_id_fkey FOREIGN KEY (contract_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE CASCADE,
  CONSTRAINT document_chunks_clause_type_check CHECK (clause_type IN ('term', 'payment', 'renewal', 'termination', 'sla', 'confidentiality', 'liability', 'indemnity', 'governing_law', 'dispute_resolution', 'ip', 'data_protection', 'force_majeure', 'assignment', 'warranty', 'insurance', 'audit', 'definitions', 'other')),
  CONSTRAINT document_chunks_id_org_key UNIQUE (id, org_id),
  CONSTRAINT document_chunks_document_id_chunk_index_key UNIQUE (document_id, chunk_index)
);
CREATE INDEX IF NOT EXISTS idx_document_chunks_contract_version_id ON public.document_chunks (contract_version_id);
CREATE INDEX IF NOT EXISTS idx_document_chunks_contract_id ON public.document_chunks (contract_id);
CREATE INDEX IF NOT EXISTS idx_document_chunks_org_id ON public.document_chunks (org_id);
DROP TRIGGER IF EXISTS trg_document_chunks_updated_at ON public.document_chunks;
CREATE TRIGGER trg_document_chunks_updated_at BEFORE UPDATE ON public.document_chunks FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- parties
CREATE TABLE IF NOT EXISTS public.parties (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text NOT NULL,
  normalized_name text NOT NULL,
  party_type text NOT NULL DEFAULT 'company',
  address text,
  identifiers jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT parties_party_type_check CHECK (party_type IN ('company', 'individual', 'government', 'other')),
  CONSTRAINT parties_id_org_key UNIQUE (id, org_id),
  CONSTRAINT parties_org_id_normalized_name_key UNIQUE (org_id, normalized_name)
);
DROP TRIGGER IF EXISTS trg_parties_updated_at ON public.parties;
CREATE TRIGGER trg_parties_updated_at BEFORE UPDATE ON public.parties FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- contract_parties
CREATE TABLE IF NOT EXISTS public.contract_parties (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL,
  party_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'other',
  confidence double precision NOT NULL DEFAULT 0.0,
  review_status text NOT NULL DEFAULT 'unreviewed',
  CONSTRAINT contract_parties_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT contract_parties_party_id_fkey FOREIGN KEY (party_id, org_id) REFERENCES public.parties (id, org_id) ON DELETE CASCADE,
  CONSTRAINT contract_parties_role_check CHECK (role IN ('customer', 'vendor', 'licensor', 'licensee', 'disclosing_party', 'receiving_party', 'landlord', 'tenant', 'partner', 'guarantor', 'other')),
  CONSTRAINT contract_parties_review_status_check CHECK (review_status IN ('unreviewed', 'needs_review', 'approved', 'rejected', 'corrected')),
  CONSTRAINT contract_parties_id_org_key UNIQUE (id, org_id),
  CONSTRAINT contract_parties_contract_id_party_id_role_key UNIQUE (contract_id, party_id, role)
);
CREATE INDEX IF NOT EXISTS idx_contract_parties_org_id ON public.contract_parties (org_id);
CREATE INDEX IF NOT EXISTS idx_contract_parties_party_id ON public.contract_parties (party_id);
DROP TRIGGER IF EXISTS trg_contract_parties_updated_at ON public.contract_parties;
CREATE TRIGGER trg_contract_parties_updated_at BEFORE UPDATE ON public.contract_parties FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- analysis_runs
CREATE TABLE IF NOT EXISTS public.analysis_runs (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid,
  contract_version_id uuid,
  run_type text NOT NULL DEFAULT 'ingest_analysis',
  status text NOT NULL DEFAULT 'queued',
  workflow_plan jsonb NOT NULL DEFAULT '{}'::jsonb,
  steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  input_summary text,
  result_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  quality_score double precision,
  error text,
  model text,
  prompt_tokens integer NOT NULL DEFAULT 0,
  completion_tokens integer NOT NULL DEFAULT 0,
  started_at timestamptz,
  finished_at timestamptz,
  requested_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  CONSTRAINT analysis_runs_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE SET NULL (contract_id),
  CONSTRAINT analysis_runs_contract_version_id_fkey FOREIGN KEY (contract_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE SET NULL (contract_version_id),
  CONSTRAINT analysis_runs_run_type_check CHECK (run_type IN ('ingest_analysis', 'question', 'compare_versions', 'risk_review', 'refresh_deadlines', 'indexing')),
  CONSTRAINT analysis_runs_status_check CHECK (status IN ('queued', 'running', 'succeeded', 'needs_review', 'failed', 'cancelled')),
  CONSTRAINT analysis_runs_id_org_key UNIQUE (id, org_id)
);
CREATE INDEX IF NOT EXISTS idx_analysis_runs_org_id_created_at ON public.analysis_runs (org_id, created_at);
CREATE INDEX IF NOT EXISTS idx_analysis_runs_contract_id ON public.analysis_runs (contract_id);
CREATE INDEX IF NOT EXISTS idx_analysis_runs_org_id ON public.analysis_runs (org_id);
CREATE INDEX IF NOT EXISTS idx_analysis_runs_contract_version_id ON public.analysis_runs (contract_version_id);
CREATE INDEX IF NOT EXISTS idx_analysis_runs_requested_by ON public.analysis_runs (requested_by);
DROP TRIGGER IF EXISTS trg_analysis_runs_updated_at ON public.analysis_runs;
CREATE TRIGGER trg_analysis_runs_updated_at BEFORE UPDATE ON public.analysis_runs FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- clauses
CREATE TABLE IF NOT EXISTS public.clauses (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL,
  contract_version_id uuid NOT NULL,
  document_id uuid,
  clause_type text NOT NULL DEFAULT 'other',
  heading text,
  section_reference text,
  page_number integer,
  text text NOT NULL,
  summary text,
  fingerprint text NOT NULL,
  confidence double precision NOT NULL DEFAULT 0.0,
  review_status text NOT NULL DEFAULT 'unreviewed',
  human_modified boolean NOT NULL DEFAULT false,
  analysis_run_id uuid,
  CONSTRAINT clauses_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT clauses_contract_version_id_fkey FOREIGN KEY (contract_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE CASCADE,
  CONSTRAINT clauses_document_id_fkey FOREIGN KEY (document_id, org_id) REFERENCES public.documents (id, org_id) ON DELETE SET NULL (document_id),
  CONSTRAINT clauses_clause_type_check CHECK (clause_type IN ('term', 'payment', 'renewal', 'termination', 'sla', 'confidentiality', 'liability', 'indemnity', 'governing_law', 'dispute_resolution', 'ip', 'data_protection', 'force_majeure', 'assignment', 'warranty', 'insurance', 'audit', 'definitions', 'other')),
  CONSTRAINT clauses_review_status_check CHECK (review_status IN ('unreviewed', 'needs_review', 'approved', 'rejected', 'corrected')),
  CONSTRAINT clauses_analysis_run_id_fkey FOREIGN KEY (analysis_run_id, org_id) REFERENCES public.analysis_runs (id, org_id) ON DELETE SET NULL (analysis_run_id),
  CONSTRAINT clauses_id_org_key UNIQUE (id, org_id),
  CONSTRAINT clauses_contract_version_id_fingerprint_key UNIQUE (contract_version_id, fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_clauses_contract_id_clause_type ON public.clauses (contract_id, clause_type);
CREATE INDEX IF NOT EXISTS idx_clauses_org_id ON public.clauses (org_id);
CREATE INDEX IF NOT EXISTS idx_clauses_contract_id ON public.clauses (contract_id);
CREATE INDEX IF NOT EXISTS idx_clauses_document_id ON public.clauses (document_id);
CREATE INDEX IF NOT EXISTS idx_clauses_analysis_run_id ON public.clauses (analysis_run_id);
DROP TRIGGER IF EXISTS trg_clauses_updated_at ON public.clauses;
CREATE TRIGGER trg_clauses_updated_at BEFORE UPDATE ON public.clauses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- obligations
CREATE TABLE IF NOT EXISTS public.obligations (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL,
  contract_version_id uuid NOT NULL,
  clause_id uuid,
  title text NOT NULL,
  description text NOT NULL,
  category text NOT NULL DEFAULT 'other',
  responsible_party_id uuid,
  responsible_party_name text,
  beneficiary_party_id uuid,
  beneficiary_name text,
  trigger text,
  conditions text,
  frequency text,
  deadline_text text,
  owner_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending',
  review_status text NOT NULL DEFAULT 'unreviewed',
  confidence double precision NOT NULL DEFAULT 0.0,
  uncertainty text,
  fingerprint text NOT NULL,
  human_modified boolean NOT NULL DEFAULT false,
  is_recurring boolean NOT NULL DEFAULT false,
  dispute_flag boolean NOT NULL DEFAULT false,
  analysis_run_id uuid,
  completed_at timestamptz,
  completed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  CONSTRAINT obligations_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT obligations_contract_version_id_fkey FOREIGN KEY (contract_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE CASCADE,
  CONSTRAINT obligations_clause_id_fkey FOREIGN KEY (clause_id, org_id) REFERENCES public.clauses (id, org_id) ON DELETE SET NULL (clause_id),
  CONSTRAINT obligations_category_check CHECK (category IN ('payment', 'delivery', 'reporting', 'notice', 'compliance', 'confidentiality', 'service_level', 'renewal', 'termination', 'insurance', 'audit', 'other')),
  CONSTRAINT obligations_responsible_party_id_fkey FOREIGN KEY (responsible_party_id, org_id) REFERENCES public.parties (id, org_id) ON DELETE SET NULL (responsible_party_id),
  CONSTRAINT obligations_beneficiary_party_id_fkey FOREIGN KEY (beneficiary_party_id, org_id) REFERENCES public.parties (id, org_id) ON DELETE SET NULL (beneficiary_party_id),
  CONSTRAINT obligations_status_check CHECK (status IN ('pending', 'in_progress', 'completed', 'disputed', 'waived')),
  CONSTRAINT obligations_review_status_check CHECK (review_status IN ('unreviewed', 'needs_review', 'approved', 'rejected', 'corrected')),
  CONSTRAINT obligations_analysis_run_id_fkey FOREIGN KEY (analysis_run_id, org_id) REFERENCES public.analysis_runs (id, org_id) ON DELETE SET NULL (analysis_run_id),
  CONSTRAINT obligations_id_org_key UNIQUE (id, org_id),
  CONSTRAINT obligations_contract_version_id_fingerprint_key UNIQUE (contract_version_id, fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_obligations_contract_id_status ON public.obligations (contract_id, status);
CREATE INDEX IF NOT EXISTS idx_obligations_org_id_owner_id ON public.obligations (org_id, owner_id);
CREATE INDEX IF NOT EXISTS idx_obligations_org_id_review_status ON public.obligations (org_id, review_status);
CREATE INDEX IF NOT EXISTS idx_obligations_org_id ON public.obligations (org_id);
CREATE INDEX IF NOT EXISTS idx_obligations_contract_id ON public.obligations (contract_id);
CREATE INDEX IF NOT EXISTS idx_obligations_clause_id ON public.obligations (clause_id);
CREATE INDEX IF NOT EXISTS idx_obligations_responsible_party_id ON public.obligations (responsible_party_id);
CREATE INDEX IF NOT EXISTS idx_obligations_beneficiary_party_id ON public.obligations (beneficiary_party_id);
CREATE INDEX IF NOT EXISTS idx_obligations_owner_id ON public.obligations (owner_id);
CREATE INDEX IF NOT EXISTS idx_obligations_analysis_run_id ON public.obligations (analysis_run_id);
CREATE INDEX IF NOT EXISTS idx_obligations_completed_by ON public.obligations (completed_by);
DROP TRIGGER IF EXISTS trg_obligations_updated_at ON public.obligations;
CREATE TRIGGER trg_obligations_updated_at BEFORE UPDATE ON public.obligations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- obligation_dependencies
CREATE TABLE IF NOT EXISTS public.obligation_dependencies (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  obligation_id uuid NOT NULL,
  depends_on_obligation_id uuid NOT NULL,
  dependency_type text NOT NULL DEFAULT 'finish_to_start',
  notes text,
  CONSTRAINT obligation_dependencies_obligation_id_fkey FOREIGN KEY (obligation_id, org_id) REFERENCES public.obligations (id, org_id) ON DELETE CASCADE,
  CONSTRAINT obligation_dependencies_depends_on_obligation_id_fkey FOREIGN KEY (depends_on_obligation_id, org_id) REFERENCES public.obligations (id, org_id) ON DELETE CASCADE,
  CONSTRAINT obligation_dependencies_dependency_type_check CHECK (dependency_type IN ('finish_to_start', 'event', 'other')),
  CONSTRAINT obligation_dependencies_id_org_key UNIQUE (id, org_id),
  CONSTRAINT obligation_dependencies_obligation_id_depends_on_obligation_id_key UNIQUE (obligation_id, depends_on_obligation_id)
);
CREATE INDEX IF NOT EXISTS idx_obligation_dependencies_org_id ON public.obligation_dependencies (org_id);
CREATE INDEX IF NOT EXISTS idx_obligation_dependencies_depends_on_obligation_id ON public.obligation_dependencies (depends_on_obligation_id);
DROP TRIGGER IF EXISTS trg_obligation_dependencies_updated_at ON public.obligation_dependencies;
CREATE TRIGGER trg_obligation_dependencies_updated_at BEFORE UPDATE ON public.obligation_dependencies FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- obligation_notes
CREATE TABLE IF NOT EXISTS public.obligation_notes (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  obligation_id uuid NOT NULL,
  kind text NOT NULL DEFAULT 'note',
  body text NOT NULL,
  attachment_path text,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  CONSTRAINT obligation_notes_obligation_id_fkey FOREIGN KEY (obligation_id, org_id) REFERENCES public.obligations (id, org_id) ON DELETE CASCADE,
  CONSTRAINT obligation_notes_kind_check CHECK (kind IN ('note', 'completion_evidence', 'dispute', 'exception')),
  CONSTRAINT obligation_notes_id_org_key UNIQUE (id, org_id)
);
CREATE INDEX IF NOT EXISTS idx_obligation_notes_obligation_id ON public.obligation_notes (obligation_id);
CREATE INDEX IF NOT EXISTS idx_obligation_notes_org_id ON public.obligation_notes (org_id);
CREATE INDEX IF NOT EXISTS idx_obligation_notes_author_id ON public.obligation_notes (author_id);
DROP TRIGGER IF EXISTS trg_obligation_notes_updated_at ON public.obligation_notes;
CREATE TRIGGER trg_obligation_notes_updated_at BEFORE UPDATE ON public.obligation_notes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- events
CREATE TABLE IF NOT EXISTS public.events (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL,
  event_type text NOT NULL DEFAULT 'custom',
  name text NOT NULL,
  occurred_on date,
  description text,
  recorded_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  CONSTRAINT events_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT events_event_type_check CHECK (event_type IN ('invoice_received', 'notice_sent', 'notice_received', 'delivery_accepted', 'service_start', 'termination_notice', 'custom')),
  CONSTRAINT events_id_org_key UNIQUE (id, org_id)
);
CREATE INDEX IF NOT EXISTS idx_events_contract_id ON public.events (contract_id);
CREATE INDEX IF NOT EXISTS idx_events_org_id ON public.events (org_id);
CREATE INDEX IF NOT EXISTS idx_events_recorded_by ON public.events (recorded_by);
DROP TRIGGER IF EXISTS trg_events_updated_at ON public.events;
CREATE TRIGGER trg_events_updated_at BEFORE UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- deadlines
CREATE TABLE IF NOT EXISTS public.deadlines (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL,
  contract_version_id uuid NOT NULL,
  obligation_id uuid,
  kind text NOT NULL DEFAULT 'unresolved',
  category text NOT NULL DEFAULT 'other',
  label text NOT NULL,
  due_date date,
  due_at timestamptz,
  timezone text NOT NULL DEFAULT 'UTC',
  anchor_event text,
  anchor_date date,
  trigger_event_id uuid,
  depends_on_deadline_id uuid,
  calculation_rule jsonb NOT NULL DEFAULT '{}'::jsonb,
  calculation_trace jsonb NOT NULL DEFAULT '[]'::jsonb,
  assumptions jsonb NOT NULL DEFAULT '[]'::jsonb,
  missing_anchors jsonb NOT NULL DEFAULT '[]'::jsonb,
  recurrence jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_clause_id uuid,
  validation_status text NOT NULL DEFAULT 'pending_review',
  status text NOT NULL DEFAULT 'open',
  escalation_level integer NOT NULL DEFAULT 0,
  fingerprint text NOT NULL,
  human_modified boolean NOT NULL DEFAULT false,
  analysis_run_id uuid,
  CONSTRAINT deadlines_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT deadlines_contract_version_id_fkey FOREIGN KEY (contract_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE CASCADE,
  CONSTRAINT deadlines_obligation_id_fkey FOREIGN KEY (obligation_id, org_id) REFERENCES public.obligations (id, org_id) ON DELETE CASCADE,
  CONSTRAINT deadlines_kind_check CHECK (kind IN ('explicit', 'derived', 'event_triggered', 'recurring', 'unresolved')),
  CONSTRAINT deadlines_category_check CHECK (category IN ('renewal_notice', 'expiration', 'termination_notice', 'payment', 'delivery', 'reporting', 'other')),
  CONSTRAINT deadlines_trigger_event_id_fkey FOREIGN KEY (trigger_event_id, org_id) REFERENCES public.events (id, org_id) ON DELETE SET NULL (trigger_event_id),
  CONSTRAINT deadlines_depends_on_deadline_id_fkey FOREIGN KEY (depends_on_deadline_id, org_id) REFERENCES public.deadlines (id, org_id) ON DELETE SET NULL (depends_on_deadline_id),
  CONSTRAINT deadlines_source_clause_id_fkey FOREIGN KEY (source_clause_id, org_id) REFERENCES public.clauses (id, org_id) ON DELETE SET NULL (source_clause_id),
  CONSTRAINT deadlines_validation_status_check CHECK (validation_status IN ('confirmed', 'pending_review', 'unresolved', 'rejected')),
  CONSTRAINT deadlines_status_check CHECK (status IN ('open', 'done', 'missed', 'waived')),
  CONSTRAINT deadlines_analysis_run_id_fkey FOREIGN KEY (analysis_run_id, org_id) REFERENCES public.analysis_runs (id, org_id) ON DELETE SET NULL (analysis_run_id),
  CONSTRAINT deadlines_id_org_key UNIQUE (id, org_id),
  CONSTRAINT deadlines_contract_version_id_fingerprint_key UNIQUE (contract_version_id, fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_deadlines_org_id_due_date ON public.deadlines (org_id, due_date);
CREATE INDEX IF NOT EXISTS idx_deadlines_contract_id ON public.deadlines (contract_id);
CREATE INDEX IF NOT EXISTS idx_deadlines_obligation_id ON public.deadlines (obligation_id);
CREATE INDEX IF NOT EXISTS idx_deadlines_org_id ON public.deadlines (org_id);
CREATE INDEX IF NOT EXISTS idx_deadlines_trigger_event_id ON public.deadlines (trigger_event_id);
CREATE INDEX IF NOT EXISTS idx_deadlines_depends_on_deadline_id ON public.deadlines (depends_on_deadline_id);
CREATE INDEX IF NOT EXISTS idx_deadlines_source_clause_id ON public.deadlines (source_clause_id);
CREATE INDEX IF NOT EXISTS idx_deadlines_analysis_run_id ON public.deadlines (analysis_run_id);
DROP TRIGGER IF EXISTS trg_deadlines_updated_at ON public.deadlines;
CREATE TRIGGER trg_deadlines_updated_at BEFORE UPDATE ON public.deadlines FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- evidence
CREATE TABLE IF NOT EXISTS public.evidence (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL,
  contract_version_id uuid NOT NULL,
  document_id uuid,
  chunk_id uuid,
  subject_type text NOT NULL,
  subject_id uuid NOT NULL,
  field_name text,
  page_number integer,
  section_reference text,
  quote text NOT NULL,
  quote_hash text NOT NULL,
  char_start integer,
  char_end integer,
  verified boolean NOT NULL DEFAULT false,
  verification_method text,
  analysis_run_id uuid,
  CONSTRAINT evidence_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT evidence_contract_version_id_fkey FOREIGN KEY (contract_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE CASCADE,
  CONSTRAINT evidence_document_id_fkey FOREIGN KEY (document_id, org_id) REFERENCES public.documents (id, org_id) ON DELETE SET NULL (document_id),
  CONSTRAINT evidence_chunk_id_fkey FOREIGN KEY (chunk_id, org_id) REFERENCES public.document_chunks (id, org_id) ON DELETE SET NULL (chunk_id),
  CONSTRAINT evidence_subject_type_check CHECK (subject_type IN ('contract', 'party', 'clause', 'obligation', 'deadline', 'finding', 'amendment', 'answer')),
  CONSTRAINT evidence_analysis_run_id_fkey FOREIGN KEY (analysis_run_id, org_id) REFERENCES public.analysis_runs (id, org_id) ON DELETE SET NULL (analysis_run_id),
  CONSTRAINT evidence_id_org_key UNIQUE (id, org_id)
);
CREATE INDEX IF NOT EXISTS idx_evidence_subject_type_subject_id ON public.evidence (subject_type, subject_id);
CREATE INDEX IF NOT EXISTS idx_evidence_contract_id ON public.evidence (contract_id);
CREATE INDEX IF NOT EXISTS idx_evidence_document_id ON public.evidence (document_id);
CREATE INDEX IF NOT EXISTS idx_evidence_org_id ON public.evidence (org_id);
CREATE INDEX IF NOT EXISTS idx_evidence_contract_version_id ON public.evidence (contract_version_id);
CREATE INDEX IF NOT EXISTS idx_evidence_chunk_id ON public.evidence (chunk_id);
CREATE INDEX IF NOT EXISTS idx_evidence_analysis_run_id ON public.evidence (analysis_run_id);
DROP TRIGGER IF EXISTS trg_evidence_updated_at ON public.evidence;
CREATE TRIGGER trg_evidence_updated_at BEFORE UPDATE ON public.evidence FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- analysis_findings
CREATE TABLE IF NOT EXISTS public.analysis_findings (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL,
  contract_version_id uuid,
  run_id uuid,
  finding_type text NOT NULL DEFAULT 'risk_signal',
  severity text NOT NULL DEFAULT 'medium',
  signal_category text NOT NULL DEFAULT 'business_risk',
  title text NOT NULL,
  description text NOT NULL,
  clause_id uuid,
  obligation_id uuid,
  deadline_id uuid,
  evidence_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  contributions jsonb NOT NULL DEFAULT '{}'::jsonb,
  weight double precision NOT NULL DEFAULT 0.0,
  status text NOT NULL DEFAULT 'open',
  review_status text NOT NULL DEFAULT 'unreviewed',
  confidence double precision NOT NULL DEFAULT 0.0,
  fingerprint text NOT NULL,
  CONSTRAINT analysis_findings_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT analysis_findings_contract_version_id_fkey FOREIGN KEY (contract_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE SET NULL (contract_version_id),
  CONSTRAINT analysis_findings_run_id_fkey FOREIGN KEY (run_id, org_id) REFERENCES public.analysis_runs (id, org_id) ON DELETE SET NULL (run_id),
  CONSTRAINT analysis_findings_finding_type_check CHECK (finding_type IN ('risk_signal', 'missing_information', 'ambiguity', 'conflict', 'unassigned_obligation', 'deadline_exposure', 'playbook_deviation', 'unsupported_claim', 'extraction_quality', 'prompt_injection', 'amendment_change')),
  CONSTRAINT analysis_findings_severity_check CHECK (severity IN ('info', 'low', 'medium', 'high', 'critical')),
  CONSTRAINT analysis_findings_signal_category_check CHECK (signal_category IN ('business_risk', 'extraction_uncertainty')),
  CONSTRAINT analysis_findings_clause_id_fkey FOREIGN KEY (clause_id, org_id) REFERENCES public.clauses (id, org_id) ON DELETE SET NULL (clause_id),
  CONSTRAINT analysis_findings_obligation_id_fkey FOREIGN KEY (obligation_id, org_id) REFERENCES public.obligations (id, org_id) ON DELETE SET NULL (obligation_id),
  CONSTRAINT analysis_findings_deadline_id_fkey FOREIGN KEY (deadline_id, org_id) REFERENCES public.deadlines (id, org_id) ON DELETE SET NULL (deadline_id),
  CONSTRAINT analysis_findings_status_check CHECK (status IN ('open', 'acknowledged', 'resolved', 'dismissed')),
  CONSTRAINT analysis_findings_review_status_check CHECK (review_status IN ('unreviewed', 'needs_review', 'approved', 'rejected', 'corrected')),
  CONSTRAINT analysis_findings_id_org_key UNIQUE (id, org_id),
  CONSTRAINT analysis_findings_contract_id_fingerprint_key UNIQUE (contract_id, fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_analysis_findings_org_id_status ON public.analysis_findings (org_id, status);
CREATE INDEX IF NOT EXISTS idx_analysis_findings_org_id ON public.analysis_findings (org_id);
CREATE INDEX IF NOT EXISTS idx_analysis_findings_contract_version_id ON public.analysis_findings (contract_version_id);
CREATE INDEX IF NOT EXISTS idx_analysis_findings_run_id ON public.analysis_findings (run_id);
CREATE INDEX IF NOT EXISTS idx_analysis_findings_clause_id ON public.analysis_findings (clause_id);
CREATE INDEX IF NOT EXISTS idx_analysis_findings_obligation_id ON public.analysis_findings (obligation_id);
CREATE INDEX IF NOT EXISTS idx_analysis_findings_deadline_id ON public.analysis_findings (deadline_id);
DROP TRIGGER IF EXISTS trg_analysis_findings_updated_at ON public.analysis_findings;
CREATE TRIGGER trg_analysis_findings_updated_at BEFORE UPDATE ON public.analysis_findings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- review_cases
CREATE TABLE IF NOT EXISTS public.review_cases (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid,
  finding_id uuid,
  run_id uuid,
  subject_type text NOT NULL DEFAULT 'contract',
  subject_id uuid,
  title text NOT NULL,
  reason text NOT NULL,
  priority text NOT NULL DEFAULT 'medium',
  status text NOT NULL DEFAULT 'open',
  assignee_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  decision text,
  decision_notes text,
  decided_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  decided_at timestamptz,
  proposed_change jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT review_cases_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT review_cases_finding_id_fkey FOREIGN KEY (finding_id, org_id) REFERENCES public.analysis_findings (id, org_id) ON DELETE SET NULL (finding_id),
  CONSTRAINT review_cases_run_id_fkey FOREIGN KEY (run_id, org_id) REFERENCES public.analysis_runs (id, org_id) ON DELETE SET NULL (run_id),
  CONSTRAINT review_cases_subject_type_check CHECK (subject_type IN ('contract', 'party', 'clause', 'obligation', 'deadline', 'finding', 'amendment', 'answer')),
  CONSTRAINT review_cases_priority_check CHECK (priority IN ('info', 'low', 'medium', 'high', 'critical')),
  CONSTRAINT review_cases_status_check CHECK (status IN ('open', 'in_review', 'resolved', 'dismissed')),
  CONSTRAINT review_cases_decision_check CHECK (decision IN ('approved', 'rejected', 'corrected', 'escalated')),
  CONSTRAINT review_cases_id_org_key UNIQUE (id, org_id)
);
CREATE INDEX IF NOT EXISTS idx_review_cases_org_id_status ON public.review_cases (org_id, status);
CREATE INDEX IF NOT EXISTS idx_review_cases_contract_id ON public.review_cases (contract_id);
CREATE INDEX IF NOT EXISTS idx_review_cases_org_id ON public.review_cases (org_id);
CREATE INDEX IF NOT EXISTS idx_review_cases_finding_id ON public.review_cases (finding_id);
CREATE INDEX IF NOT EXISTS idx_review_cases_run_id ON public.review_cases (run_id);
CREATE INDEX IF NOT EXISTS idx_review_cases_assignee_id ON public.review_cases (assignee_id);
CREATE INDEX IF NOT EXISTS idx_review_cases_decided_by ON public.review_cases (decided_by);
DROP TRIGGER IF EXISTS trg_review_cases_updated_at ON public.review_cases;
CREATE TRIGGER trg_review_cases_updated_at BEFORE UPDATE ON public.review_cases FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- alerts
CREATE TABLE IF NOT EXISTS public.alerts (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid,
  obligation_id uuid,
  deadline_id uuid,
  alert_type text NOT NULL DEFAULT 'system',
  severity text NOT NULL DEFAULT 'medium',
  title text NOT NULL,
  message text NOT NULL,
  due_on date,
  status text NOT NULL DEFAULT 'unread',
  dedupe_key text NOT NULL,
  escalation_level integer NOT NULL DEFAULT 0,
  acknowledged_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  acknowledged_at timestamptz,
  CONSTRAINT alerts_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT alerts_obligation_id_fkey FOREIGN KEY (obligation_id, org_id) REFERENCES public.obligations (id, org_id) ON DELETE CASCADE,
  CONSTRAINT alerts_deadline_id_fkey FOREIGN KEY (deadline_id, org_id) REFERENCES public.deadlines (id, org_id) ON DELETE CASCADE,
  CONSTRAINT alerts_alert_type_check CHECK (alert_type IN ('renewal_window', 'deadline_approaching', 'deadline_overdue', 'unassigned_obligation', 'unresolved_deadline', 'review_aging', 'contract_expiring', 'system')),
  CONSTRAINT alerts_severity_check CHECK (severity IN ('info', 'low', 'medium', 'high', 'critical')),
  CONSTRAINT alerts_status_check CHECK (status IN ('unread', 'acknowledged', 'resolved', 'dismissed')),
  CONSTRAINT alerts_id_org_key UNIQUE (id, org_id),
  CONSTRAINT alerts_org_id_dedupe_key_key UNIQUE (org_id, dedupe_key)
);
CREATE INDEX IF NOT EXISTS idx_alerts_org_id_status ON public.alerts (org_id, status);
CREATE INDEX IF NOT EXISTS idx_alerts_deadline_id ON public.alerts (deadline_id);
CREATE INDEX IF NOT EXISTS idx_alerts_contract_id ON public.alerts (contract_id);
CREATE INDEX IF NOT EXISTS idx_alerts_obligation_id ON public.alerts (obligation_id);
CREATE INDEX IF NOT EXISTS idx_alerts_acknowledged_by ON public.alerts (acknowledged_by);
DROP TRIGGER IF EXISTS trg_alerts_updated_at ON public.alerts;
CREATE TRIGGER trg_alerts_updated_at BEFORE UPDATE ON public.alerts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- amendments
CREATE TABLE IF NOT EXISTS public.amendments (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL,
  base_version_id uuid NOT NULL,
  amendment_version_id uuid NOT NULL,
  summary text,
  changes jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'draft',
  run_id uuid,
  CONSTRAINT amendments_contract_id_fkey FOREIGN KEY (contract_id, org_id) REFERENCES public.contracts (id, org_id) ON DELETE CASCADE,
  CONSTRAINT amendments_base_version_id_fkey FOREIGN KEY (base_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE CASCADE,
  CONSTRAINT amendments_amendment_version_id_fkey FOREIGN KEY (amendment_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE CASCADE,
  CONSTRAINT amendments_status_check CHECK (status IN ('draft', 'reviewed')),
  CONSTRAINT amendments_run_id_fkey FOREIGN KEY (run_id, org_id) REFERENCES public.analysis_runs (id, org_id) ON DELETE SET NULL (run_id),
  CONSTRAINT amendments_id_org_key UNIQUE (id, org_id),
  CONSTRAINT amendments_base_version_id_amendment_version_id_key UNIQUE (base_version_id, amendment_version_id)
);
CREATE INDEX IF NOT EXISTS idx_amendments_contract_id ON public.amendments (contract_id);
CREATE INDEX IF NOT EXISTS idx_amendments_org_id ON public.amendments (org_id);
CREATE INDEX IF NOT EXISTS idx_amendments_amendment_version_id ON public.amendments (amendment_version_id);
CREATE INDEX IF NOT EXISTS idx_amendments_run_id ON public.amendments (run_id);
DROP TRIGGER IF EXISTS trg_amendments_updated_at ON public.amendments;
CREATE TRIGGER trg_amendments_updated_at BEFORE UPDATE ON public.amendments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- playbook_rules
CREATE TABLE IF NOT EXISTS public.playbook_rules (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  clause_type text,
  rule_type text NOT NULL,
  params jsonb NOT NULL DEFAULT '{}'::jsonb,
  severity text NOT NULL DEFAULT 'medium',
  enabled boolean NOT NULL DEFAULT true,
  CONSTRAINT playbook_rules_clause_type_check CHECK (clause_type IN ('term', 'payment', 'renewal', 'termination', 'sla', 'confidentiality', 'liability', 'indemnity', 'governing_law', 'dispute_resolution', 'ip', 'data_protection', 'force_majeure', 'assignment', 'warranty', 'insurance', 'audit', 'definitions', 'other')),
  CONSTRAINT playbook_rules_rule_type_check CHECK (rule_type IN ('require_clause', 'max_notice_days', 'min_notice_days', 'forbid_auto_renewal', 'forbid_phrase', 'max_payment_days', 'require_governing_law')),
  CONSTRAINT playbook_rules_severity_check CHECK (severity IN ('info', 'low', 'medium', 'high', 'critical')),
  CONSTRAINT playbook_rules_id_org_key UNIQUE (id, org_id),
  CONSTRAINT playbook_rules_org_id_name_key UNIQUE (org_id, name)
);
DROP TRIGGER IF EXISTS trg_playbook_rules_updated_at ON public.playbook_rules;
CREATE TRIGGER trg_playbook_rules_updated_at BEFORE UPDATE ON public.playbook_rules FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- integrations
CREATE TABLE IF NOT EXISTS public.integrations (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  provider text NOT NULL,
  name text NOT NULL,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  enabled boolean NOT NULL DEFAULT false,
  requires_confirmation boolean NOT NULL DEFAULT true,
  allowed_actions jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  CONSTRAINT integrations_provider_check CHECK (provider IN ('calendar_ics', 'webhook')),
  CONSTRAINT integrations_id_org_key UNIQUE (id, org_id),
  CONSTRAINT integrations_org_id_name_key UNIQUE (org_id, name)
);
CREATE INDEX IF NOT EXISTS idx_integrations_created_by ON public.integrations (created_by);
DROP TRIGGER IF EXISTS trg_integrations_updated_at ON public.integrations;
CREATE TRIGGER trg_integrations_updated_at BEFORE UPDATE ON public.integrations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- audit_logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  actor_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_email text,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  before jsonb,
  after jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT audit_logs_id_org_key UNIQUE (id, org_id)
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_org_id_created_at ON public.audit_logs (org_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_type_entity_id ON public.audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_org_id ON public.audit_logs (org_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_id ON public.audit_logs (actor_id);
DROP TRIGGER IF EXISTS trg_audit_logs_updated_at ON public.audit_logs;
CREATE TRIGGER trg_audit_logs_updated_at BEFORE UPDATE ON public.audit_logs FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- circular references added after all tables exist

ALTER TABLE public.contracts DROP CONSTRAINT IF EXISTS contracts_current_version_id_fkey;
ALTER TABLE public.contracts ADD CONSTRAINT contracts_current_version_id_fkey FOREIGN KEY (current_version_id, org_id) REFERENCES public.contract_versions (id, org_id) ON DELETE SET NULL (current_version_id);
