-- GENERATED by scripts/generate_migrations.py from app/models. DO NOT EDIT BY HAND.

-- Row Level Security policies and audit triggers.

-- organizations
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS organizations_select ON public.organizations;
CREATE POLICY organizations_select ON public.organizations FOR SELECT TO authenticated
  USING (public.is_org_member(id));
DROP POLICY IF EXISTS organizations_update ON public.organizations;
CREATE POLICY organizations_update ON public.organizations FOR UPDATE TO authenticated
  USING (public.has_org_role(id, ARRAY['owner', 'admin']))
  WITH CHECK (public.has_org_role(id, ARRAY['owner', 'admin']));
DROP POLICY IF EXISTS organizations_delete ON public.organizations;
CREATE POLICY organizations_delete ON public.organizations FOR DELETE TO authenticated
  USING (public.has_org_role(id, ARRAY['owner']));

-- profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS profiles_select ON public.profiles;
CREATE POLICY profiles_select ON public.profiles FOR SELECT TO authenticated
  USING (id = auth.uid() OR public.shares_org_with(id));
DROP POLICY IF EXISTS profiles_insert ON public.profiles;
CREATE POLICY profiles_insert ON public.profiles FOR INSERT TO authenticated
  WITH CHECK (id = auth.uid());
DROP POLICY IF EXISTS profiles_update ON public.profiles;
CREATE POLICY profiles_update ON public.profiles FOR UPDATE TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- organization_members
ALTER TABLE public.organization_members ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS organization_members_select ON public.organization_members;
CREATE POLICY organization_members_select ON public.organization_members FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS organization_members_insert ON public.organization_members;
CREATE POLICY organization_members_insert ON public.organization_members FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin']));
DROP POLICY IF EXISTS organization_members_update ON public.organization_members;
CREATE POLICY organization_members_update ON public.organization_members FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin']));
DROP POLICY IF EXISTS organization_members_delete ON public.organization_members;
CREATE POLICY organization_members_delete ON public.organization_members FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin']));
DROP TRIGGER IF EXISTS trg_organization_members_audit ON public.organization_members;
CREATE TRIGGER trg_organization_members_audit AFTER INSERT OR UPDATE OR DELETE ON public.organization_members FOR EACH ROW EXECUTE FUNCTION public.audit_row_change();

-- contracts
ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS contracts_select ON public.contracts;
CREATE POLICY contracts_select ON public.contracts FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS contracts_insert ON public.contracts;
CREATE POLICY contracts_insert ON public.contracts FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS contracts_update ON public.contracts;
CREATE POLICY contracts_update ON public.contracts FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS contracts_delete ON public.contracts;
CREATE POLICY contracts_delete ON public.contracts FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));
DROP TRIGGER IF EXISTS trg_contracts_audit ON public.contracts;
CREATE TRIGGER trg_contracts_audit AFTER INSERT OR UPDATE OR DELETE ON public.contracts FOR EACH ROW EXECUTE FUNCTION public.audit_row_change();

-- contract_versions
ALTER TABLE public.contract_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS contract_versions_select ON public.contract_versions;
CREATE POLICY contract_versions_select ON public.contract_versions FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS contract_versions_insert ON public.contract_versions;
CREATE POLICY contract_versions_insert ON public.contract_versions FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS contract_versions_update ON public.contract_versions;
CREATE POLICY contract_versions_update ON public.contract_versions FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS contract_versions_delete ON public.contract_versions;
CREATE POLICY contract_versions_delete ON public.contract_versions FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));
DROP TRIGGER IF EXISTS trg_contract_versions_audit ON public.contract_versions;
CREATE TRIGGER trg_contract_versions_audit AFTER INSERT OR UPDATE OR DELETE ON public.contract_versions FOR EACH ROW EXECUTE FUNCTION public.audit_row_change();

-- documents
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS documents_select ON public.documents;
CREATE POLICY documents_select ON public.documents FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS documents_insert ON public.documents;
CREATE POLICY documents_insert ON public.documents FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS documents_update ON public.documents;
CREATE POLICY documents_update ON public.documents FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS documents_delete ON public.documents;
CREATE POLICY documents_delete ON public.documents FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));
DROP TRIGGER IF EXISTS trg_documents_audit ON public.documents;
CREATE TRIGGER trg_documents_audit AFTER INSERT OR UPDATE OR DELETE ON public.documents FOR EACH ROW EXECUTE FUNCTION public.audit_row_change();

-- document_chunks
ALTER TABLE public.document_chunks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS document_chunks_select ON public.document_chunks;
CREATE POLICY document_chunks_select ON public.document_chunks FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS document_chunks_insert ON public.document_chunks;
CREATE POLICY document_chunks_insert ON public.document_chunks FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS document_chunks_update ON public.document_chunks;
CREATE POLICY document_chunks_update ON public.document_chunks FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS document_chunks_delete ON public.document_chunks;
CREATE POLICY document_chunks_delete ON public.document_chunks FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- parties
ALTER TABLE public.parties ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS parties_select ON public.parties;
CREATE POLICY parties_select ON public.parties FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS parties_insert ON public.parties;
CREATE POLICY parties_insert ON public.parties FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS parties_update ON public.parties;
CREATE POLICY parties_update ON public.parties FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS parties_delete ON public.parties;
CREATE POLICY parties_delete ON public.parties FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- contract_parties
ALTER TABLE public.contract_parties ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS contract_parties_select ON public.contract_parties;
CREATE POLICY contract_parties_select ON public.contract_parties FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS contract_parties_insert ON public.contract_parties;
CREATE POLICY contract_parties_insert ON public.contract_parties FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS contract_parties_update ON public.contract_parties;
CREATE POLICY contract_parties_update ON public.contract_parties FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS contract_parties_delete ON public.contract_parties;
CREATE POLICY contract_parties_delete ON public.contract_parties FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- analysis_runs
ALTER TABLE public.analysis_runs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS analysis_runs_select ON public.analysis_runs;
CREATE POLICY analysis_runs_select ON public.analysis_runs FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS analysis_runs_insert ON public.analysis_runs;
CREATE POLICY analysis_runs_insert ON public.analysis_runs FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS analysis_runs_update ON public.analysis_runs;
CREATE POLICY analysis_runs_update ON public.analysis_runs FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS analysis_runs_delete ON public.analysis_runs;
CREATE POLICY analysis_runs_delete ON public.analysis_runs FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- clauses
ALTER TABLE public.clauses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS clauses_select ON public.clauses;
CREATE POLICY clauses_select ON public.clauses FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS clauses_insert ON public.clauses;
CREATE POLICY clauses_insert ON public.clauses FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS clauses_update ON public.clauses;
CREATE POLICY clauses_update ON public.clauses FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS clauses_delete ON public.clauses;
CREATE POLICY clauses_delete ON public.clauses FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- obligations
ALTER TABLE public.obligations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS obligations_select ON public.obligations;
CREATE POLICY obligations_select ON public.obligations FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS obligations_insert ON public.obligations;
CREATE POLICY obligations_insert ON public.obligations FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS obligations_update ON public.obligations;
CREATE POLICY obligations_update ON public.obligations FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS obligations_delete ON public.obligations;
CREATE POLICY obligations_delete ON public.obligations FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));
DROP TRIGGER IF EXISTS trg_obligations_audit ON public.obligations;
CREATE TRIGGER trg_obligations_audit AFTER INSERT OR UPDATE OR DELETE ON public.obligations FOR EACH ROW EXECUTE FUNCTION public.audit_row_change();

-- obligation_dependencies
ALTER TABLE public.obligation_dependencies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS obligation_dependencies_select ON public.obligation_dependencies;
CREATE POLICY obligation_dependencies_select ON public.obligation_dependencies FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS obligation_dependencies_insert ON public.obligation_dependencies;
CREATE POLICY obligation_dependencies_insert ON public.obligation_dependencies FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS obligation_dependencies_update ON public.obligation_dependencies;
CREATE POLICY obligation_dependencies_update ON public.obligation_dependencies FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS obligation_dependencies_delete ON public.obligation_dependencies;
CREATE POLICY obligation_dependencies_delete ON public.obligation_dependencies FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- obligation_notes
ALTER TABLE public.obligation_notes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS obligation_notes_select ON public.obligation_notes;
CREATE POLICY obligation_notes_select ON public.obligation_notes FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS obligation_notes_insert ON public.obligation_notes;
CREATE POLICY obligation_notes_insert ON public.obligation_notes FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS obligation_notes_update ON public.obligation_notes;
CREATE POLICY obligation_notes_update ON public.obligation_notes FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS obligation_notes_delete ON public.obligation_notes;
CREATE POLICY obligation_notes_delete ON public.obligation_notes FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- events
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS events_select ON public.events;
CREATE POLICY events_select ON public.events FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS events_insert ON public.events;
CREATE POLICY events_insert ON public.events FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS events_update ON public.events;
CREATE POLICY events_update ON public.events FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS events_delete ON public.events;
CREATE POLICY events_delete ON public.events FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- deadlines
ALTER TABLE public.deadlines ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS deadlines_select ON public.deadlines;
CREATE POLICY deadlines_select ON public.deadlines FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS deadlines_insert ON public.deadlines;
CREATE POLICY deadlines_insert ON public.deadlines FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS deadlines_update ON public.deadlines;
CREATE POLICY deadlines_update ON public.deadlines FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS deadlines_delete ON public.deadlines;
CREATE POLICY deadlines_delete ON public.deadlines FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));
DROP TRIGGER IF EXISTS trg_deadlines_audit ON public.deadlines;
CREATE TRIGGER trg_deadlines_audit AFTER INSERT OR UPDATE OR DELETE ON public.deadlines FOR EACH ROW EXECUTE FUNCTION public.audit_row_change();

-- evidence
ALTER TABLE public.evidence ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS evidence_select ON public.evidence;
CREATE POLICY evidence_select ON public.evidence FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS evidence_insert ON public.evidence;
CREATE POLICY evidence_insert ON public.evidence FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS evidence_update ON public.evidence;
CREATE POLICY evidence_update ON public.evidence FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS evidence_delete ON public.evidence;
CREATE POLICY evidence_delete ON public.evidence FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- analysis_findings
ALTER TABLE public.analysis_findings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS analysis_findings_select ON public.analysis_findings;
CREATE POLICY analysis_findings_select ON public.analysis_findings FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS analysis_findings_insert ON public.analysis_findings;
CREATE POLICY analysis_findings_insert ON public.analysis_findings FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS analysis_findings_update ON public.analysis_findings;
CREATE POLICY analysis_findings_update ON public.analysis_findings FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS analysis_findings_delete ON public.analysis_findings;
CREATE POLICY analysis_findings_delete ON public.analysis_findings FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- review_cases
ALTER TABLE public.review_cases ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS review_cases_select ON public.review_cases;
CREATE POLICY review_cases_select ON public.review_cases FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS review_cases_insert ON public.review_cases;
CREATE POLICY review_cases_insert ON public.review_cases FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS review_cases_update ON public.review_cases;
CREATE POLICY review_cases_update ON public.review_cases FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));
DROP POLICY IF EXISTS review_cases_delete ON public.review_cases;
CREATE POLICY review_cases_delete ON public.review_cases FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));
DROP TRIGGER IF EXISTS trg_review_cases_audit ON public.review_cases;
CREATE TRIGGER trg_review_cases_audit AFTER INSERT OR UPDATE OR DELETE ON public.review_cases FOR EACH ROW EXECUTE FUNCTION public.audit_row_change();

-- alerts
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS alerts_select ON public.alerts;
CREATE POLICY alerts_select ON public.alerts FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS alerts_insert ON public.alerts;
CREATE POLICY alerts_insert ON public.alerts FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS alerts_update ON public.alerts;
CREATE POLICY alerts_update ON public.alerts FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS alerts_delete ON public.alerts;
CREATE POLICY alerts_delete ON public.alerts FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));

-- amendments
ALTER TABLE public.amendments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS amendments_select ON public.amendments;
CREATE POLICY amendments_select ON public.amendments FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS amendments_insert ON public.amendments;
CREATE POLICY amendments_insert ON public.amendments FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS amendments_update ON public.amendments;
CREATE POLICY amendments_update ON public.amendments FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager', 'member']));
DROP POLICY IF EXISTS amendments_delete ON public.amendments;
CREATE POLICY amendments_delete ON public.amendments FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));
DROP TRIGGER IF EXISTS trg_amendments_audit ON public.amendments;
CREATE TRIGGER trg_amendments_audit AFTER INSERT OR UPDATE OR DELETE ON public.amendments FOR EACH ROW EXECUTE FUNCTION public.audit_row_change();

-- playbook_rules
ALTER TABLE public.playbook_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS playbook_rules_select ON public.playbook_rules;
CREATE POLICY playbook_rules_select ON public.playbook_rules FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
DROP POLICY IF EXISTS playbook_rules_insert ON public.playbook_rules;
CREATE POLICY playbook_rules_insert ON public.playbook_rules FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer']));
DROP POLICY IF EXISTS playbook_rules_update ON public.playbook_rules;
CREATE POLICY playbook_rules_update ON public.playbook_rules FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer']));
DROP POLICY IF EXISTS playbook_rules_delete ON public.playbook_rules;
CREATE POLICY playbook_rules_delete ON public.playbook_rules FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer']));
DROP TRIGGER IF EXISTS trg_playbook_rules_audit ON public.playbook_rules;
CREATE TRIGGER trg_playbook_rules_audit AFTER INSERT OR UPDATE OR DELETE ON public.playbook_rules FOR EACH ROW EXECUTE FUNCTION public.audit_row_change();

-- integrations
ALTER TABLE public.integrations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS integrations_select ON public.integrations;
CREATE POLICY integrations_select ON public.integrations FOR SELECT TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer', 'contract_manager']));
DROP POLICY IF EXISTS integrations_insert ON public.integrations;
CREATE POLICY integrations_insert ON public.integrations FOR INSERT TO authenticated
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin']));
DROP POLICY IF EXISTS integrations_update ON public.integrations;
CREATE POLICY integrations_update ON public.integrations FOR UPDATE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin']))
  WITH CHECK (public.has_org_role(org_id, ARRAY['owner', 'admin']));
DROP POLICY IF EXISTS integrations_delete ON public.integrations;
CREATE POLICY integrations_delete ON public.integrations FOR DELETE TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin']));
DROP TRIGGER IF EXISTS trg_integrations_audit ON public.integrations;
CREATE TRIGGER trg_integrations_audit AFTER INSERT OR UPDATE OR DELETE ON public.integrations FOR EACH ROW EXECUTE FUNCTION public.audit_row_change();

-- audit_logs
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS audit_logs_select ON public.audit_logs;
CREATE POLICY audit_logs_select ON public.audit_logs FOR SELECT TO authenticated
  USING (public.has_org_role(org_id, ARRAY['owner', 'admin', 'legal_reviewer']));
